# Generated by Django 4.1.3 on 2022-12-09 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aadharcard_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('is_aadhar_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('Central Bank Of India', 'Central Bank Of India'), ('State Bank Of India', 'State Bank Of India'), ('HDFC', 'HDFC'), ('Punjab National Bank ', 'Punjab National Bank '), ('Bank Of Baroda', 'Bank Of Baroda')], max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('re_enter_account_number', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Email_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('otp', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('nominee_proof_identy', models.FileField(upload_to='')),
                ('relation_with_nominee', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Retired', 'Retired'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Housewife', 'Housewife')], max_length=100)),
                ('percentage_of_share', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('is_phone_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('watchlist1', models.CharField(max_length=20)),
                ('watchlist2', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Intraday', 'Intraday'), ('Longterm', 'Longterm')], max_length=250)),
                ('stock', models.CharField(choices=[('NSE', 'NSE'), ('BSE', 'BSE')], max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(max_length=250)),
                ('ltp', models.IntegerField()),
                ('validity', models.CharField(choices=[('Day', 'Day'), ('IOC', 'IOC')], max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('order_set_date', models.DateTimeField(auto_now_add=True)),
                ('order_reach_date', models.DateTimeField(blank=True, null=True)),
                ('lists', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myaccount.watchlist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharcard_no', models.CharField(max_length=12, unique=True)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('marritul_status', models.CharField(max_length=50)),
                ('profession', models.CharField(choices=[('Salaried', 'Salaried'), ('Buisiness', 'Buisiness'), ('Retired', 'Retired'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Unemployed', 'Unemployed'), ('Housewife', 'Housewife')], max_length=50)),
                ('sub_profession', models.CharField(max_length=50)),
                ('annual_income', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=255)),
                ('pancard_no', models.CharField(max_length=20, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.IntegerField(default='0')),
                ('enter_amount', models.IntegerField(default='0')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
